feat: add rollback in cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -118,7 +118,13 @@ jobs:
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:${{ github.sha }}
           # Use feat/test-cicd as the 'stable' branch for now
           if [ "${{ github.ref }}" == "refs/heads/feat/test-cicd" ] || [ "${{ github.ref }}" == "refs/heads/feat/testcase" ]; then
+
+            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:${{ github.sha }} \
+                      ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:stable
+
+            # Push both latest + stable
             docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:latest
+            docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:stable
           fi
 
   deploy:
@@ -144,5 +150,28 @@ jobs:
             
             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:latest
-            DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:latest docker compose up -d --force-recreate
 
+            RUN_MIGRATIONS=true DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:latest docker compose up -d --force-recreate
+
+            echo "Waiting for container to become healthy..."
+
+            for i in {1..10}; do
+              STATUS=$(docker inspect --format='{{.State.Health.Status}}' bookshelf-api || echo "starting")
+
+              echo "Health status: $STATUS"
+
+              if [ "$STATUS" = "healthy" ]; then
+                echo "Deployment successful "
+                exit 0
+              fi
+
+              sleep 5
+            done
+
+            echo "Deployment failed  — triggering rollback..."
+
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:stable
+
+            DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/bookshelf:stable docker compose up -d
+
+            exit 1
